### ISSUE TITLE
Target "lirixwaylandplugin" links to target "Qt5::WaylandCompositorPrivate"

### ISSUE THREAD

**Issue by yuxue521** [lirios/qml-xwayland#7]
* Taglib
 * PipeWire

-- Configuring done
CMake Error at libraries/cmake-shared/modules/LiriAddQmlPlugin.cmake:87 (add_library):
  Target "lirixwaylandplugin" links to target "Qt5::WaylandCompositorPrivate"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  desktop/qml-xwayland/src/xwayland/CMakeLists.txt:5 (liri_add_qml_plugin)

Is it because of the qt version? I use qt5.11.3

**Comment by MightyM17** [comment]
> del
> Qt5::WaylandCompositorPrivate
> build ok

How did you fix it?

**Comment by plfiorini** [comment]
Qt5::WaylandCompositorPrivate is a cmake target provided by qtwayland.
If you don't have it you have a broken installation.
Try again with Qt 5.15.
